#!/usr/bin/env bash
# debug nginx server
sed -i "s/user\swww-data;/user nginx;/" /etc/nginx/nginx.conf
first="listen\s[0-9]*?\sdefault_server"
second="listen 80 default_server"
start="listen\s\[::\]:[0-9]*?\sdefault_server"
end="listen [::]:80 default_server"
sudo sed -ri "s/$first/$second/" /etc/nginx/sites-available/default
sudo sed -ri "s/$start/$end/" /etc/nginx/sites-available/default
sudo sed -ri "s/$first/$second/" /etc/nginx/sites-enabled/default
sudo sed -ri "s/$start/$end/" /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo service apache2 stop
sudo -u	nginx service nginx restart
