#!/usr/bin/env bash
# debug nginx server
sed -i 1d file /etc/nginx/nginx.conf
sudo sed -ri "s/listen\s[0-9]*?\sdefault_server/listen 8080 default_server/" /etc/nginx/sites-available/default
sudo sed -ri "s/listen\s[0-9]*?\sdefault_server/listen 8080 default_server/" /etc/nginx/sites-enabled/default
sudo sed -ri "s/listen\s\[::\]:[0-9]*?\sdefault_server/listen [::]:8080 default_server/" /etc/nginx/sites-available/default
sudo sed -ri "s/listen\s\[::\]:[0-9]*?\sdefault_server/listen [::]:8080 default_server/" /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
touch /run/nginx.pid
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /var/log/nginx/error.log
chown nginx:nginx /var/log/nginx/access.log
chown nginx:nginx /run/nginx.pid
sudo service apache2 stop
sudo -u	nginx service nginx restart
