#!/usr/bin/env bash
# debug nginx server
sudo sed -ri "s/[0-9]*?\sdefault_server/8080 default_server/" /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
touch nginx:nginx
chown nginx:nginx /etc/nginx/nginx.conf /var/log/nginx/error.log /var/log/nginx/access.log /run/nginx.pid
sudo service apache2 stop
sudo -u	nginx service nginx restart
