#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/page404.html
echo "Ceci n'est pas une page" > /var/www/html/page404.html
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        error_page 404 /page404.html;
        server_name _;
	add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
"
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.html
echo "$config" > /etc/nginx/sites-available/default
sudo service nginx restart
