#!/usr/bin/env bash
# install nginx
first="s/listen\s[0-9].*/"
second="listen 80 default_server;"
start="listen\s\[::\]:[0-9].*"
end="listen [::]:80 default_server;"
sudo sed -ri "s/$start/$end/" /etc/nginx/sites-available/default
sudo service nginx restart
