#!/usr/bin/env bash
# install nginx
start="listen\s\[::\]:80\sdefault_server\sipv6only=on;"
end="listen [::]:80 default_server;"
sudo sed -ri "s/$start/$end/" /etc/nginx/sites-available/default
sudo service nginx restart
