#!/usr/bin/env bash
# debug ngix server
sudo sed -ri "s/[0-9]*?\sdefault_server/80 default_server/g" /etc/nginx/sites-available/default
sudo sed -ri "s/[0-9]*?\sdefault_server/80 default_server/g" /etc/nginx/sites-enabled/default
echo "" | sed tee nginx.pid > /dev/null 2&>1
