#!/usr/bin/env bash
# Install nginx web server

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
