#!/usr/bin/env bash
# Install nginx web server

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
