#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install -y nginx
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }
	location /redirect_me {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
}
"
echo $config > /etc/nginx/sites-available/default
sudo service nginx restart
