#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update -y
sudo apt-get install -y nginx
echo " Ceci n'est pas une page" | sudo tee /var/www/html/page404.html
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	error_page 404 /var/www/html/page404.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
        }
}
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "$config" > /etc/nginx/sites-available/default
sudo service nginx restart
